Updated CI/CD pipelines for automated test integration

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,11 +18,27 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Run tests
-        run: cd toxic8ball; npm i; npm test
+      - name: Check Pull Request Title
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            if [[ ! "${{ github.event.pull_request.title }}" =~ "New Feature" ]]; then
+              echo "Pull request title does not contain 'New Feature'"
+              exit 0
+            fi
+          fi
+
+          if ! git diff --name-only HEAD HEAD~1 | grep -qE '\.test\.js$'; then
+            echo "Unit test file not found"
+            exit 0
+          fi
+
+          run: cd toxic8ball; npm i; npm test        
 
       - name: Lint code
         run: cd toxic8ball; npm i; npm run lint
 
       - name: Generate documentation
         run: cd toxic8ball; npm i; npm run docs
+      
+      
+
